from intelligraphs.generators.synthetic.synpaths_generator import SynPathsGenerator
from intelligraphs.generators.synthetic.syntipr_generator import SynTIPRGenerator
from intelligraphs.generators.synthetic.syntypes_generator import SynTypesGenerator