package:
  name: intelligraphs
  version: 1.0.14

source:
  git_url: https://github.com/thiviyanT/intelligraphs.git
  git_tag: v1.0.14

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  build:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8,<3.12.0a0
    - pip
    - tqdm
    - bokeh
    - graphviz
    - requests
    - pytorch::pytorch

about:
  home: https://github.com/thiviyanT/intelligraphs
  license: CC-BY 4.0
  summary: A Python package for loading and using IntelliGraphs benchmarking datasets.
  author: Thiviyan Thanapalasingam
  author_email: thiviyan.t@gmail.com
  description: A Python package for loading and using IntelliGraphs benchmarking datasets.
