package:
  name: intelligraphs
  version: 1.0.4

source:
  git_url: https://github.com/thiviyanT/intelligraphs.git
  git_tag: v1.0.4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.8
    - pip
  build:
    - python >=3.8
    - setuptools
  run:
    - python >=3.8,<3.12.0a0
    - tqdm
    - bokeh
    - graphviz
    - requests
    - pytorch::pytorch

about:
  home: https://github.com/thiviyanT/intelligraphs
  license: MIT
  summary: A simple library to generate synthetic Knowledge Graphs using random triples.
  author: Thiviyan Thanapalasingam
  author_email: thiviyan.t@gmail.com
  description: A simple library to generate synthetic Knowledge Graphs using random triples.
