dutch_cities = {
    "The Hague",
    "Amsterdam",
    "Utrecht",
    "Rotterdam",
    "Eindhoven",
    "Almere",
    "Groningen",
    "Breda",
    "Apeldoorn",
    "Haarlem",
    "Zaanstad",
    "Arnhem",
    "’s-Hertogenbosch",
    "Leeuwarden",
    "Maastricht",
    "Zwolle",
    "Alphen aan den Rijn",
    "Emmen",
    "Delft",
    "Deventer",
    "Hilversum",
    "Heerlen",
    "Purmerend",
    "Lelystad",
    "Roosendaal",
    "Spijkenisse",
    "Ede",
    "Gouda",
    "Zaandam",
    "Bergen op Zoom",
    "Capelle aan den IJssel",
    "Veenendaal",
    "Katwijk",
    "Zeist",
    "Nieuwegein",
    "Assen",
    "Hardenberg",
    "Barneveld",
    "Roermond",
    "Heerhugowaard",
    "Oosterhout",
    "Den Helder",
    "Hoogeveen",
    "Kampen",
    "Woerden",
    "Houten",
    "Sittard",
    "IJmuiden",
    "Middelburg"
}
