names = {
    'Eveleen Eszes',
    'Meera Mac Amhalghaidh',
    'Cleophas Erős',
    'Vanja Rutkowski',
    'Hildr Liang',
    'Hüseyn Mikkelsen',
    'Schwanhild Patel',
    'Wolodymyr Plamondon',
    'Martina Alan',
    'Nirmala Kwiatkowski',
    'Gríðr Oberst',
    'Aneirin Logan',
    'Pili Barbier',
    'Danya Maçon',
    'Vesta Corna',
    'Priscilla Stringer',
    'Rhianon Van Rompu'
    'Valerija Alger',
    'Renáta Park',
    'Anita McCabe',
    'Rahul Rowan',
    'Lulu MacKay',
    'Aeson Pinheiro',
    'Toshe Pander',
    'Salvator Cousineau',
    'Tahlako Plaskett',
    'Teófilo Gupta',
    'Yonit Stojanovski',
    'Terminus Ó Coigligh',
    'Erna Van Dijk',
    'Hildegard Dávid',
    'Hilda Milošević',
    'Bogdan Baglio',
    'Eldar Dawson',
    'Anaïs Hajós',
    'Boglárka Rosenberg',
    'Božidar Bullard',
    'Anselm Sulzbach',
    'Toygar Pesce',
    'Nikita Serafim',
    'Diindiisi Fortuyn',
    'Amalia Görög',
    'Kunti Andréasson',
    'Romana Sitko',
    'Athanas Blackbug',
    'Marjan Albert',
    'Drusus Krejči',
    'Livnat Hull',
    'Casimir Darnell',
    'Vojtech Mac Neachtain',
    'Lída McDaniel',
}

roles = {
    'professor',
    'assistant professor',
    'post doctoral researcher',
    'phd researcher',
    'masters researcher',
}

years = range(1950, 2023)