# These are fictional names created using a name generator
names = {
    'Aeson Pinheiro',
    'Amalia Görög',
    'Anaïs Hajós',
    'Aneirin Logan',
    'Anita McCabe',
    'Anselm Sulzbach',
    'Athanas Blackbug',
    'Bogdan Baglio',
    'Boglárka Rosenberg',
    'Božidar Bullard',
    'Casimir Darnell',
    'Cleophas Erős',
    'Danya Maçon',
    'Diindiisi Fortuyn',
    'Drusus Krejči',
    'Eldar Dawson',
    'Erna Van Dijk',
    'Eveleen Eszes',
    'Gríðr Oberst',
    'Hilda Milošević',
    'Hildegard Dávid',
    'Hildr Liang',
    'Hüseyn Mikkelsen',
    'Kunti Andréasson',
    'Livnat Hull',
    'Lulu MacKay',
    'Lída McDaniel',
    'Marjan Albert',
    'Martina Alan',
    'Meera Mac Amhalghaidh',
    'Nikita Serafim',
    'Nirmala Kwiatkowski',
    'Pili Barbier',
    'Priscilla Stringer',
    'Rahul Rowan',
    'Renáta Park',
    'Rhianon Van Rompu',
    'Romana Sitko',
    'Salvator Cousineau',
    'Schwanhild Patel',
    'Tahlako Plaskett',
    'Terminus Ó Coigligh',
    'Teófilo Gupta',
    'Toshe Pander',
    'Toygar Pesce',
    'Valerija Alger',
    'Vanja Rutkowski',
    'Vesta Corna',
    'Vojtech Mac Neachtain',
    'Wolodymyr Plamondon',
    'Yonit Stojanovski'
}

roles = {
    'professor',
    'assistant professor',
    'post doctoral researcher',
    'phd researcher',
    'masters researcher',
}

years = range(1950, 2023)